#!/usr/bin/python

# Ini adalah Baris Identitas:
"""
Nama: Riva Rizkiana Ramadhani
Email: riva.riskiana111@gmail.com
"""


#impor numerical python (numpy)
import numpy as np

#impor pustaka plot
from matplotlib import pyplot as plt

#data dasar
# Percepatan gravitasi ('g')= 9.8 m / s^2
g = 9.8
# Kecepatan awal lemparan ('v0')= 8 m/s
v0 = 8
# Sudut Lemparan awal = Pi/4
k = np.linspace(0,2*np.pi,100)

# Bentuk persamaan :



# Koordinat t
t  = 0
dt = 0.01
t = t + dt

# Koordinat y merupakan fungsi dalam x
y = np.sin (k) * t - 0.5 * g * t^2



# Tampilkan Grafik
plt.plot (t,y)
plt. title ('Grafik gerak benda yang dilemparkan di atas permukaan bumi dalam variabel x')
plt.xlabel('Jarak di sumbu x')
plt.ylabel ('Ketinggian')
plt.show()







